site_name: Obsidian Librarian
site_description: An intelligent content management system for Obsidian vaults
site_author: Obsidian Librarian Team
site_url: https://obsidian-librarian.dev
repo_url: https://github.com/obsidian-librarian/obsidian-librarian
repo_name: obsidian-librarian/obsidian-librarian

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: tutorials/getting-started.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide.md
    - Core Features: user-guide/features.md
    - CLI Reference: user-guide/cli.md
    - Best Practices: user-guide/best-practices.md
  - API Reference:
    - Overview: api-reference.md
    - Core Classes: api/core.md
    - Services: api/services.md
    - Models: api/models.md
  - Tutorials:
    - Getting Started: tutorials/getting-started.md
    - Research Workflow: tutorials/research-workflow.md
    - Automation: tutorials/automation.md
  - Development:
    - Contributing: contributing.md
    - Architecture: development/architecture.md
    - Testing: development/testing.md
  - About:
    - Changelog: changelog.md
    - License: license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/obsidian-librarian
    - icon: fontawesome/brands/discord
      link: https://discord.gg/obsidian-librarian
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/obsidianlib

copyright: Copyright &copy; 2024 Obsidian Librarian Team